/**
 * Catalog strings for en.
 *
 * Generated by projecting the shared {ko,en,ja} tables onto one language so
 * a visitor downloads only the language they read. Edit the string for a
 * module here; the getters that consume it live in `i18n/localizedData`.
 */
import type { CatalogStrings } from '../localizedData';

const CATALOG: CatalogStrings = {
  "apps": {
    "smartfactory": {
      "name": "Smart Factory Suite",
      "categoryLabel": "Manufacturing Operation Suite",
      "desc": "Modular MES suite customized with industry-specific quality and record modules",
      "detail": "Modular MES suite compliant with industry standards across general manufacturing, food/cosmetics, and pharma/biotech. Interacts strictly via the B²LAB ontology layer rather than direct legacy DB connections, enabling zero-downtime plug-and-play integration.",
      "unit": "Per-module pricing"
    },
    "a2lab": {
      "name": "A²LAB (AI Model Generator)",
      "categoryLabel": "AI Module Generation",
      "desc": "Build and train industrial AI agent modules like predictive quality and maintenance with no-code",
      "detail": "Empowers domain engineers to upload datasets and run automated AutoML pipelines directly in a web UI without Python code. Generated lightweight models are packaged to on-premise nodes for sub-millisecond real-time inference.",
      "unit": "Base fee + Inference usage"
    },
    "orch": {
      "name": "Multi-AI Agent Supervisor",
      "categoryLabel": "AI Orchestration",
      "desc": "Cross-verifies decisions of domain-specific agents from A²LAB and orchestrates process control",
      "detail": "Monitors and arbitrates conflicting decisions between quality inspection, energy saving, and AGV dispatch agents. Control commands exceeding safety thresholds strictly require on-site operator approval gates.",
      "unit": "Per active agent module"
    },
    "consensbot": {
      "name": "ConsensBot (Regulatory sLM)",
      "categoryLabel": "On-premise sLM",
      "desc": "Learns in-house SOPs and GMP guidelines to analyze deviations and draft audit reports",
      "detail": "On-premises specialized small language model (sLM) that guarantees zero bytes of internal SOPs/GMP documents leave the corporate firewall. Rapidly answers audit queries and drafts regulatory compliance reports with source document citations.",
      "unit": "Concurrent user license"
    },
    "aesg": {
      "name": "A.ESG / A.Station",
      "categoryLabel": "Energy & ESG",
      "desc": "Collects real-time electricity and gas metrics to reduce carbon emissions and cap peak power",
      "detail": "Automates electrical peak shaving and greenhouse gas Scope 1 & 2 inventory reporting. Correlates with B²LAB ontology machine profiles to balance daily production schedules against energy peak tariffs.",
      "unit": "Per sensor tag"
    },
    "twin": {
      "name": "Digital Twin (3D Process)",
      "categoryLabel": "3D Process Visualization",
      "desc": "Visualizes factory layout, real-time machine status, and bottlenecks in an interactive 3D canvas",
      "detail": "Renders telemetry, alarm states, and AGV locations on a WebGL 3D canvas in real time. Enables intuitive virtual facility walk-throughs in standard modern browsers without proprietary thick clients.",
      "unit": "Per facility and line"
    },
    "arcmind": {
      "name": "ArcMind (No-Code Platform Builder)",
      "categoryLabel": "In-House IT Platform Builder",
      "desc": "Dedicated builder for enterprises with in-house IT to build proprietary Smart Factory systems via No-Code/Low-Code without off-the-shelf MES",
      "detail": "A dedicated builder for enterprises with in-house IT engineering teams. Instead of purchasing off-the-shelf MES suites, internal IT teams build 100% tailored work order dispatchers, shopfloor views, daily KPI dashboards, and business logic using No-Code/Low-Code on top of standardized B²LAB ontology data.",
      "unit": "Enterprise builder license (Seats & authoring)"
    },
    "b2lab": {
      "name": "B²LAB Ontology Datalake",
      "categoryLabel": "Mandatory Core Foundation",
      "desc": "Data backbone that virtualizes diverse in-house domain DBs into standard ontology schemas",
      "detail": "A shared foundation module priced separately from the platform base fee. It brokers heterogeneous in-house databases (MES, ERP, equipment PLC) through AAS, OPC-UA and KS X 9101, so installing a new module never means editing existing system code. Any module that reads domain data needs this layer in place first.",
      "unit": "KRW 800K/mo (1TB included)"
    }
  },
  "subModules": {
    "mes-pharma": {
      "name": "Pharma-Specific MES",
      "desc": "GMP batch tracking, deviation handling, and validation data auditing",
      "unitLabel": "800k KRW/line/mo"
    },
    "mes-food": {
      "name": "Food/Cosmetics MES",
      "desc": "HACCP critical control point (CCP) auto-logging, raw material traceability & expiry management",
      "unitLabel": "600k KRW/line/mo"
    },
    "mes-general": {
      "name": "General Manufacturing MES",
      "desc": "Production execution, real-time LOT tracking, OEE utilization analysis, N-POP barcode sync",
      "unitLabel": "400k KRW/line/mo"
    },
    "ebrs": {
      "name": "EBRS (Electronic Batch Records)",
      "desc": "FDA 21 CFR Part 11 electronic signature and audit trail compliance record management",
      "unitLabel": "Base 1.2M KRW/mo (Batch scaled)"
    },
    "rems": {
      "name": "REMS (Cleanroom Environmental Monitoring)",
      "desc": "Real-time differential pressure, temperature/humidity, particle count collection & alarms",
      "unitLabel": "Base 900k KRW/mo (200 measurement points included, +15% per 100)"
    },
    "scm": {
      "name": "SCM (Supply Chain Collaboration)",
      "desc": "Raw material procurement, lead time tracking, Tier 1 & 2 subcontractor portal integration",
      "unitLabel": "Base 1.0M KRW/mo (10 supplier accounts included, +20% per 10)"
    }
  },
  "groupLabels": {
    "MES 코어 (상호 배타적 · 1종 필수 선택)": "MES Core (Mutually Exclusive · 1 Required Selection)",
    "품질 · 기록 · 공급망 확장 모듈 (자유 조합)": "Quality, Record & SCM Addon Modules (Flexible Combination)"
  },
  "deps": {
    "B²LAB 온톨로지 데이터레이크": {
      "name": "B²LAB Ontology Datalake",
      "desc": "Separately subscribed (shared foundation module)"
    },
    "ArcTunnel mTLS 게이트웨이": {
      "name": "ArcTunnel mTLS Gateway",
      "desc": "On-premises node connected (4ms latency)"
    },
    "KS X 9101 설비 데이터 규격": {
      "name": "KS X 9101 Equipment Data Standard",
      "desc": "Facility production line PLC mapping verified"
    },
    "B²LAB 데이터레이크 (AAS 온톨로지)": {
      "name": "B²LAB Datalake (AAS Ontology)",
      "desc": "Separately subscribed (active data pipeline)"
    },
    "GPU 가속 추론 노드 (NVIDIA TensorRT)": {
      "name": "GPU Acceleration Node (NVIDIA TensorRT)",
      "desc": "On-premises edge server ready (L4 GPU)"
    },
    "A²LAB (사전 생성된 도메인 모델)": {
      "name": "A²LAB (Pre-generated domain models)",
      "desc": "Requires at least 1 domain model (3 currently deployed)"
    },
    "온프레미스 GPU 추론 서버": {
      "name": "On-Premises GPU Inference Server",
      "desc": "2x in-house NVIDIA L40S servers verified on-site"
    },
    "사내 제조 기준서(SOP) 벡터 색인": {
      "name": "In-House SOP Vector Indexing",
      "desc": "0 of 342 SOPs indexed (auto-parsed after local installation)"
    },
    "B²LAB 데이터레이크": {
      "name": "B²LAB Datalake",
      "desc": "Subscribed (Base Platform Fee)"
    },
    "사내 전력량계/유량계 태그 매핑": {
      "name": "In-House Power & Flow Meter Tag Mapping",
      "desc": "42 of 48 measurement tags mapped (6 additional required)"
    },
    "Smart Factory MES 또는 A.ESG": {
      "name": "Smart Factory MES or A.ESG",
      "desc": "Facility MES data connection ready"
    },
    "자체 IT 전산 인력": {
      "name": "In-House IT Engineering Personnel",
      "desc": "Authors of internal No-Code/Low-Code interfaces & business logic"
    },
    "A²LAB (선행 모듈)": {
      "name": "A²LAB (Prerequisite Module)",
      "desc": "Requires the prerequisite agent authoring tool (bundling recommended)"
    },
    "등록된 에이전트 모듈 3개 이상": {
      "name": "At Least 3 Registered Agent Modules",
      "desc": "1 registered at this facility (more can be created after installing A²LAB)"
    },
    "MLOps 실행엔진": {
      "name": "MLOps Execution Engine",
      "desc": "Bundled with the on-premise Docker runtime"
    }
  },
  "dataScopes": {
    "현장 온프레미스 사내 DB (방화벽 내부 보존)": "On-premises production DB (Kept behind firewall)",
    "사내 보안 파일서버 (SOP, GMP 규정 문서 342건)": "Secure in-house file server (342 SOP & GMP regulatory docs)",
    "SCADA 및 전력 계측기 시계열 DB (InfluxDB)": "SCADA & power meter time-series DB (InfluxDB)",
    "B²LAB 온톨로지 스트리밍 버스": "B²LAB Ontology Streaming Bus",
    "B²LAB 온톨로지 GraphQL & REST API": "B²LAB Ontology GraphQL & REST API",
    "사업장 레거시 DB 전체 가상화 인터페이스": "Enterprise legacy DB virtualization interface",
    "ArcMind JSON Schema 컴포넌트 규약 (KS X 9101 매핑)": "ArcMind JSON Schema component spec (KS X 9101 mapped)",
    "PDF/Docx 온톨로지 청킹 및 사내 Milvus 벡터DB": "PDF/Docx ontology chunking & in-house Milvus vector DB",
    "AAS / OPC-UA / KS X 9101 표준 온톨로지": "AAS / OPC-UA / KS X 9101 standard ontology",
    "GLTF / glTF 3D + OPC-UA Telemetry": "GLTF / glTF 3D + OPC-UA Telemetry",
    "Modbus TCP / KS X 9101": "Modbus TCP / KS X 9101",
    "AAS / OPC-UA / KS X 9101": "AAS / OPC-UA / KS X 9101",
    "ArcOS 공통 이벤트 버스 (Pub/Sub)": "ArcOS Shared Event Bus (Pub/Sub)",
    "OPC-UA / Parquet Lakehouse": "OPC-UA / Parquet Lakehouse",
    "학습 데이터는 사내 로컬 GPU 클러스터 내부에서만 순환": "Training data circulates only inside the in-house local GPU cluster",
    "에이전트 판단 신뢰도 벡터 및 결정 로그 (사내)": "Agent confidence vectors and decision logs (on-premises)"
  },
  "permissions": {
    "에이전트 간 이벤트 버스 라우팅": "Inter-agent event bus routing",
    "설비 자동 비상 정지 트리거": "Automated machine emergency stop trigger",
    "사내 문서 저장소 Read": "In-house document repository Read",
    "외부망 아웃바운드 차단 확인": "Verify external network outbound egress blocked",
    "전력 계측점 주기적 폴링": "Periodic polling of power meters",
    "피크 전력 차단기 릴레이 제어": "Peak power breaker relay control",
    "설비 3D 텔레메트리 구독": "Equipment 3D telemetry subscription",
    "화면 레이아웃 및 컴포넌트 Read/Write": "Screen layout & component Read/Write",
    "사내 온톨로지 메타데이터 카탈로그 관리": "Manage in-house ontology metadata catalog",
    "생산 라인 설비 PLC 읽기": "Production line equipment PLC read",
    "배치 완료 승인 및 전자 서명": "Batch completion approval and e-signature",
    "공정 레시피 제어 명령(Write)": "Process recipe control command (Write)",
    "센서 시계열 데이터 학습용 Read": "Sensor time-series data read for training",
    "새 에이전트 컨테이너 기동": "Launch new agent container"
  },
  "locations": {
    "[경남/사천] 항공·정밀가공 사업장": "[Sacheon] Aerospace & Precision Machining Plant",
    "[경남/창원] 기계·특수제조 사업장": "[Changwon] Machinery & Special Manufacturing Plant",
    "[충북/오송] 제약·바이오 GMP 사업장": "[Osong] Pharma & Bio GMP Plant",
    "[전북/익산] 식품·화장품 HACCP 사업장": "[Iksan] Food & Cosmetics HACCP Plant",
    "[경기/화성] 전자·반도체 부품 사업장": "[Hwaseong] Electronics & Semiconductor Plant",
    "ArcOS 제어 평면 (SaaS) 및 사내 캐시 노드": "ArcOS Control Plane (SaaS) & In-House Cache Node",
    "[충북/오송] 제약·바이오 GMP 사업장 GPU 노드": "[Osong] Pharma/Bio GMP Plant GPU Node",
    "[경남/사천] 항공·정밀가공 사업장 폐쇄망 노드": "[Sacheon] Aerospace Plant Air-Gapped Node",
    "[경남/창원] 기계·특수제조 사업장 변전실": "[Changwon] Machinery Plant Electrical Substation",
    "[전북/익산] 식품·화장품 HACCP 사업장 계측반": "[Iksan] HACCP Plant Metering Board",
    "[경남/사천] 항공·정밀가공 사업장 종합관제실": "[Sacheon] Aerospace Control Center",
    "[경기/화성] 전자·반도체 부품 사업장 모니터링룸": "[Hwaseong] Electronics Plant Monitoring Room",
    "[경남/사천] 항공·정밀가공 사업장 인스턴스": "[Sacheon] Aerospace Plant Instance",
    "[충북/오송] 제약·바이오 GMP 사업장 인스턴스": "[Osong] Pharma/Bio GMP Plant Instance",
    "[전북/익산] 식품·화장품 HACCP 사업장 인스턴스": "[Iksan] HACCP Plant Instance",
    "[경남/사천] 항공·정밀가공 사업장 온프레미스": "[Sacheon] Aerospace Plant On-Premises",
    "[충북/오송] 제약·바이오 GMP 사업장 온프레미스": "[Osong] Pharma/Bio GMP Plant On-Premises",
    "[충북/오송] 제약·바이오 GMP 사업장 (라인 #1~#4)": "[Osong] Pharma/Bio GMP Plant (Lines #1-#4)",
    "[경남/사천] 항공·정밀가공 사업장 AI 노드": "[Sacheon] Aerospace Plant AI Node",
    "[경남/창원] 기계·특수제조 사업장 AI 노드": "[Changwon] Machinery Plant AI Node",
    "[충북/오송] 제약·바이오 GMP 사업장 AI 노드": "[Osong] Pharma/Bio GMP Plant AI Node",
    "[경남/사천] 항공·정밀가공 사업장 엣지 노드": "[Sacheon] Aerospace Plant Edge Node",
    "[경기/화성] 전자·반도체 부품 사업장 엣지 노드": "[Hwaseong] Electronics Plant Edge Node"
  },
  "tenants": {
    "[경남/사천] 항공·정밀기계 제조연합": "[Sacheon] Aerospace & Precision Machinery Alliance"
  },
  "presets": {
    "preset-pharma": {
      "title": "Pharma/Bio GMP Regulatory Compliance",
      "subtitle": "GMP Validation · CFR Part 11 E-Signature · SOP sLM",
      "badge": "Compliance",
      "desc": "Combines FDA 21 CFR Part 11 electronic batch records and cleanroom monitoring with on-premise SOP-grounded deviation analysis sLM.",
      "targetAudience": "Pharma / Bio / Medical Device Manufacturers"
    },
    "preset-food": {
      "title": "Food/Cosmetics HACCP Hygiene & Traceability",
      "subtitle": "HACCP Auto Logging · Raw Material Traceability · SCM",
      "badge": "Hygiene & Trace",
      "desc": "Automates CCP logging in mixing/filling processes with forward/backward traceability connecting suppliers to finished goods and safety checks.",
      "targetAudience": "F&B / Nutraceuticals / Cosmetics Manufacturers"
    },
    "preset-precision": {
      "title": "Precision Machinery & Auto Parts Predictive Quality",
      "subtitle": "OEE Analysis · AI Defect Prediction · 3D Digital Twin",
      "badge": "Quality & Maintenance",
      "desc": "Analyzes vibration and current data from CNC machining lines for tool wear prediction and remote 3D digital twin monitoring.",
      "targetAudience": "Aerospace / Precision Machining / Tier 1 Auto Suppliers"
    },
    "preset-esg": {
      "title": "Chemical & Base Industry Energy Optimization & Safety",
      "subtitle": "Peak Power Control · GHG Inventory · Hazard Monitoring",
      "badge": "Energy & ESG",
      "desc": "Reduces energy utility bills through dynamic peak shaving on heavy machinery and continuously monitors hazardous leaks via vision AI.",
      "targetAudience": "Chemical Materials / Heat Treatment & Plating / Foundries"
    },
    "preset-starter": {
      "title": "Smart Factory Starter Essential Core",
      "subtitle": "Standard MES · Barcode Tracking · Machine Monitoring",
      "badge": "Starter Pick",
      "desc": "Low-barrier foundational package that rapidly digitizes production LOT barcode logs and machine status monitoring.",
      "targetAudience": "SMEs Adopting Smart Manufacturing For First Time"
    },
    "preset-autonomous": {
      "title": "Autonomous AI Manufacturing (Full Agent Architecture)",
      "subtitle": "AI agent generation · Supervisor orchestration · sLM regulatory analysis",
      "badge": "Autonomous AI",
      "desc": "The Multi-AI Agent Supervisor orchestrates the quality, equipment and energy agents generated in A²LAB, combined with the air-gapped ConsensBot sLM and a 3D digital twin.",
      "targetAudience": "Lighthouse factory programs / large multi-process production sites"
    },
    "preset-inhouse-diy": {
      "title": "In-House IT No-Code Platform Build (DIY)",
      "subtitle": "ArcMind no-code/low-code builder · B²LAB ontology · A²LAB · 3D twin",
      "badge": "In-House IT",
      "desc": "Instead of adopting an off-the-shelf MES suite, in-house IT staff build process screens, work instructions and mobile views themselves with ArcMind (No-Code/Low-Code) — a 100% custom platform on top of the B²LAB ontology, with no MES subscription fee.",
      "targetAudience": "Manufacturers with in-house IT staff who build their own smart factory instead of buying an off-the-shelf MES"
    },
    "preset-scm-audit": {
      "title": "Supply Chain & Supplier Quality Integration (SCM & Audit)",
      "subtitle": "Supplier purchase orders · Real-time delivery tracking · Electronic record evidence",
      "badge": "Supply Chain",
      "desc": "Links in-house processes with tier-1 and tier-2 supplier portals in real time and preserves delivery quality and PO inspection history as electronic records, so customer audits can be answered immediately.",
      "targetAudience": "Manufacturers with heavy outsourced machining and mandatory supplier audits"
    }
  },
  "facilities": {
    "aerospace-precision": {
      "fullName": "[Sacheon] Aerospace & Precision Plant",
      "subTitle": "Aerospace Machining & Composite Assembly 1 & 2"
    },
    "machinery-specialty": {
      "fullName": "[Changwon] Machinery & Heavy Industry Plant",
      "subTitle": "Heavy Rotary Machining & Defense Components Line"
    },
    "bio-pharma": {
      "fullName": "[Osong] Pharma & Bio GMP Plant",
      "subTitle": "Sterile Injectables & Finished Drug Cleanrooms"
    },
    "food-cosmetics": {
      "fullName": "[Iksan] Food & Cosmetics HACCP Plant",
      "subTitle": "Blending, Filling & HACCP CCP Tracking"
    },
    "electronics-semi": {
      "fullName": "[Hwaseong] Electronics & Semiconductor Plant",
      "subTitle": "High-Speed SMT & Automotive Electronics Assembly"
    }
  },
  "depDescriptions": {
    "온톨로지 스키마 정합성 검증 완료": "Ontology schema consistency verified",
    "플랫폼 기본료 포함 (GraphQL / REST 온톨로지 연동)": "Included in the platform base fee (GraphQL / REST ontology integration)"
  },
  "workspace": {
    "B²LAB 온톨로지 데이터레이크": "B²LAB Ontology Datalake",
    "제약 특화 MES (Smart Factory)": "Pharma-Specific MES (Smart Factory)",
    "EBRS (전자 제조기록)": "EBRS (Electronic Batch Records)",
    "SCM (공급망 협업 연계)": "SCM (Supply Chain Collaboration)",
    "AI Vision 결함 탐지 (ArcVision)": "AI Vision Defect Detection (ArcVision)",
    "A²LAB (AI 모듈 생성기)": "A²LAB (AI Model Generator)",
    "다중 AI Agent 슈퍼바이저": "Multi-AI Agent Supervisor",
    "컨센스봇 (ConsensBot)": "ConsensBot (Regulatory sLM)",
    "디지털 트윈 (Digital Twin)": "Digital Twin",
    "ArcMind (노코드/로우코드 플랫폼 빌더)": "ArcMind (No-Code/Low-Code Platform Builder)",
    "공통 기반": "Shared Core",
    "스위트 코어": "Suite Core",
    "스위트 확장": "Suite Extension",
    "에너지": "Energy",
    "시각화": "Visualization",
    "기반": "Core",
    "빌더": "Builder",
    "방금 전 (정상 수신)": "just now (healthy)",
    "3초 전 (정상 수신)": "3s ago (healthy)",
    "5초 전 (정상 수신)": "5s ago (healthy)",
    "12초 전 (정상 수신)": "12s ago (healthy)",
    "B²LAB 온톨로지 바인딩 완료": "B²LAB ontology binding complete",
    "표준 스키마 48개 태그 매핑 완료 (AAS/OPC-UA)": "Standard schema: 48 tags mapped (AAS/OPC-UA)",
    "생산 LOT 및 GMP 전자서명 로컬 기록 중": "Recording production LOTs and GMP e-signatures locally",
    "CFR Part 11 감사추적 DB 동기화 중": "Syncing the CFR Part 11 audit trail DB",
    "협력사 발주 및 납기 검수 이력 12,480건 (암호화 압축)": "Supplier PO & delivery inspection history: 12,480 records (encrypted, compressed)",
    "2029년 03월 31일 (의무 보존 5년)": "March 31, 2029 (5-year mandatory retention)",
    "사내 구매팀 ERP 직접 이관에 따른 구독 해지 후 감사용 읽기전용 보존 전환": "Subscription cancelled after migrating to the in-house purchasing ERP; converted to read-only retention for audit",
    "가공 표면 미세 스크래치 실시간 AI 검출률 99.2% 실증 및 오탐 최소화": "Demonstrate 99.2% real-time AI detection of micro-scratches on machined surfaces while minimizing false positives",
    "제조기술팀 / 김선임": "Manufacturing Engineering / Senior Engineer Kim",
    "사내 공정 적합성 실증": "In-house process suitability validation",
    "제조기술팀": "Manufacturing Engineering"
  },
  "growthMetrics": {
    "생산 라인 수 / 계측점 수 / 협력사 수": "Production lines / measurement points / supplier accounts",
    "월간 추론 호출 수 (단위: 만 건)": "Monthly inference calls (unit: 10K calls)",
    "연계 에이전트 수": "Connected agents",
    "운영 라이선스 사용자 수": "Licensed operating users",
    "실시간 전력·유틸리티 계측점 수": "Real-time power & utility measurement points",
    "디지털화 대상 사업장 면적 및 라인": "Digitized facility floor area and lines",
    "제작 대시보드 시트 수": "Authored dashboard sheets",
    "데이터 용량 구간 (기본 1TB 포함)": "Data storage tier (1TB included)"
  }
};

export default CATALOG;
